FROM ke-pasa-workers-base:latest

COPY workers/rss /app/workers/rss

RUN pip install --no-cache-dir -r /app/workers/rss/requirements.txt

COPY deploy/docker/supervisord.conf.rss /etc/supervisor/conf.d/rss-worker.conf

WORKDIR /app

EXPOSE 9001

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
