FROM ke-pasa-workers-base:latest

COPY workers/publisher /app/workers/publisher

RUN pip install --no-cache-dir -r /app/workers/publisher/requirements.txt

COPY deploy/docker/supervisord.conf.publisher /etc/supervisor/conf.d/publisher-worker.conf

WORKDIR /app

EXPOSE 9001

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
