"""Helper for posting to X (formerly Twitter) using API v2 with OAuth 2.0.

Uses OAuth 2.0 User Context with automatic token refresh.
Tokens are stored in .x_tokens.json (generated by tools/x_oauth_setup.py).
Supports dry-run via `X_DRY_RUN` environment variable.
"""
from __future__ import annotations

import os
import json
import logging
from typing import Optional, Dict, Any
from pathlib import Path
from datetime import datetime, timedelta

import requests

logger = logging.getLogger(__name__)

TOKEN_FILE = Path(__file__).parent.parent.parent / '.x_tokens.json'


def _load_tokens() -> Optional[Dict[str, Any]]:
    """Load tokens from file."""
    if not TOKEN_FILE.exists():
        return None
    try:
        return json.loads(TOKEN_FILE.read_text())
    except Exception as e:
        logger.warning(f'Failed to load tokens: {e}')
        return None


def _save_tokens(tokens: Dict[str, Any]):
    """Save tokens to file."""
    try:
        TOKEN_FILE.write_text(json.dumps(tokens, indent=2))
    except Exception as e:
        logger.error(f'Failed to save tokens: {e}')


def _refresh_access_token(refresh_token: str) -> Dict[str, Any]:
    """Refresh access token using refresh token."""
    client_id = os.environ.get('X_CLIENT_ID')
    client_secret = os.environ.get('X_CLIENT_SECRET')
    
    if not client_id:
        raise RuntimeError('X_CLIENT_ID not set in environment')
    
    url = 'https://api.twitter.com/2/oauth2/token'
    data = {
        'grant_type': 'refresh_token',
        'refresh_token': refresh_token,
        'client_id': client_id,
    }
    
    # Use client secret if available (confidential client)
    auth = (client_id, client_secret) if client_secret else None
    
    logger.info('🔄 Refreshing X access token...')
    
    try:
        resp = requests.post(url, data=data, auth=auth, timeout=30)
    except Exception as e:
        logger.exception('Failed to refresh token')
        raise RuntimeError(f'Token refresh failed: {e}')
    
    if resp.status_code != 200:
        logger.error(f'Token refresh failed: {resp.status_code} {resp.text}')
        raise RuntimeError(f'Token refresh failed: {resp.status_code}')
    
    token_data = resp.json()
    
    # Add timestamp for expiry tracking
    token_data['obtained_at'] = datetime.utcnow().isoformat()
    
    # Save new tokens
    _save_tokens(token_data)
    
    logger.info('✅ Access token refreshed')
    return token_data


def _get_valid_access_token() -> str:
    """Get valid access token, refreshing if necessary."""
    tokens = _load_tokens()
    
    if not tokens:
        raise RuntimeError(
            'No tokens found. Run tools/x_oauth_setup.py first to authorize the app.'
        )
    
    access_token = tokens.get('access_token')
    refresh_token = tokens.get('refresh_token')
    expires_in = tokens.get('expires_in', 7200)  # Default 2 hours
    obtained_at_str = tokens.get('obtained_at')
    
    if not access_token or not refresh_token:
        raise RuntimeError('Invalid token data. Re-run tools/x_oauth_setup.py')
    
    # Check if token needs refresh (refresh 5 minutes before expiry)
    if obtained_at_str:
        try:
            obtained_at = datetime.fromisoformat(obtained_at_str)
            expiry_time = obtained_at + timedelta(seconds=expires_in - 300)
            
            if datetime.utcnow() >= expiry_time:
                logger.info('Access token expired, refreshing...')
                new_tokens = _refresh_access_token(refresh_token)
                access_token = new_tokens.get('access_token')
        except Exception as e:
            logger.warning(f'Failed to check token expiry: {e}')
    
    return access_token


def post_tweet(text: str, trim_to_280: bool = True) -> Dict[str, Any]:
    """Post `text` to X (Twitter) using v2 API with OAuth 2.0 and return parsed JSON result.

    Args:
        text: Status text to post (will be trimmed to 280 chars by default).
        trim_to_280: If True, truncate text to 280 characters.

    Returns:
        Dict with tweet data including 'id' and 'text'.

    Raises:
        RuntimeError on failure.
    """
    if not text:
        raise ValueError('text is required')

    if trim_to_280 and len(text) > 280:
        text = text[:277] + '...'

    # Dry-run support
    dry_run = os.environ.get('X_DRY_RUN', '')
    if dry_run and str(dry_run).lower() in ('1', 'true', 'yes', 'on'):
        logger.info('🧪 X_DRY_RUN enabled — not posting to X, returning mock response')
        return {'data': {'id': 'mock_12345', 'text': text[:280]}, 'mock': True, 'status': 'dry_run'}

    # Get valid access token (refreshes automatically if needed)
    try:
        access_token = _get_valid_access_token()
    except Exception as e:
        logger.error(f'Failed to get access token: {e}')
        raise

    logger.info(f'📤 Posting to X (v2 API with OAuth 2.0): {text[:50]}...')
    
    url = 'https://api.twitter.com/2/tweets'
    headers = {
        'Authorization': f'Bearer {access_token}',
        'Content-Type': 'application/json',
    }
    payload = {'text': text}

    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=30)
    except Exception as e:
        logger.exception('❌ X post request failed')
        raise RuntimeError(f'X post request failed: {e}')

    try:
        j = resp.json()
    except Exception:
        logger.error(f'❌ X returned non-JSON response: {resp.status_code} {resp.text[:200]}')
        raise RuntimeError(f'X returned non-JSON response: {resp.status_code} {resp.text}')

    if not (resp.status_code in (200, 201) and isinstance(j, dict) and j.get('data')):
        logger.error(f'❌ X API v2 error: status={resp.status_code} body={j}')
        error_detail = j.get('errors', [{}])[0] if j.get('errors') else j
        raise RuntimeError(f'X API v2 error: status={resp.status_code} detail={error_detail}')

    tweet_id = j['data'].get('id')
    logger.info(f'✅ X post successful: id={tweet_id}')
    return j


__all__ = ['post_tweet']
